version: "3.8"

services:
  mysql:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zigs_db
    ports:
      - "3307:3306"

  backend:
    build: .
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/zigs_db